const data = [
    {
        id:'1',
        projectName:'DelawareRanch',
        createdDate:'31/05/2024',
        status:'active'
    },
    {
        id:'2',
        projectName:'GreenMallard',
        createdDate:'20/06/2024',
        status:'active'
    },
    {
        id:'3',
        projectName:'DelawareRanch',
        createdDate:'31/05/2024',
        status:'inctive'
    },
    {
        id:'4',
        projectName:'MarketMaster',
        createdDate:'24/06/2024',
        status:'active'
    },
    {
        id:'5',
        projectName:'BusinessBoos',
        createdDate:'13/06/2024',
        status:'inctive'
    },
    {
        id:'6',
        projectName:'ProfitPlanner',
        createdDate:'10/06/2024',
        status:'active'
    },
    {
        id:'7',
        projectName:'DelawareRanch',
        createdDate:'15/07/2024',
        status:'inctive'
    },
    {
        id:'8',
        projectName:'BizBuddy',
        createdDate:'22/07/2024',
        status:'active'
    },
    {
        id:'9',
        projectName:'TradeTalk',
        createdDate:'31/05/2024',
        status:'inctive'
    },
    {
        id:'10',
        projectName:'CommerceCompanion',
        createdDate:'31/05/2024',
        status:'active'
    }

]
export default data;